# Generated by Django 3.2.5 on 2021-07-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='desription',
            new_name='description',
        ),
    ]
