# Generated by Django 3.2.5 on 2021-07-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210704_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='large',
            field=models.ImageField(blank=True, default='profile1.png', upload_to='avatars/large'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='medium',
            field=models.ImageField(blank=True, default='profile1.png', upload_to='avatars/medium'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='thumbnail',
            field=models.ImageField(blank=True, default='profile1.png', upload_to='avatars/thumbnail'),
        ),
    ]
