# Generated by Django 3.2.5 on 2021-07-05 06:09

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_avatar_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': (28.154, -25.7484), 'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'}, null=True)),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(blank=True, map_id='map', null=True)),
            ],
        ),
    ]
